# Generated by Django 5.2.3 on 2025-06-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='core/account/users/', verbose_name='Сурет'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'Пайдаланушы'), ('student', 'Оқушы'), ('teacher', 'Мұғалім')], default='user', max_length=32, verbose_name='Қолданушы типі'),
        ),
    ]
