# Generated by Django 5.2.3 on 2025-07-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_avatar_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Қолданушы', 'verbose_name_plural': 'Қолданушылар'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'Қолданушы'), ('student', 'Оқушы'), ('teacher', 'Мұғалім')], default='user', max_length=32, verbose_name='Қолданушы типі'),
        ),
    ]
