# Generated by Django 5.2.3 on 2025-07-13 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_options_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Анықтамасы')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модульдер',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Сұрақ мәтіні')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реті')),
            ],
            options={
                'verbose_name': 'Сұрақ',
                'verbose_name_plural': 'Сұрақтар',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='core/models/subject/posters', verbose_name='Постер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Анықтамасы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Уақыты')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='Қаралым')),
                ('cert', models.FileField(blank=True, null=True, upload_to='core/models/subject/certs', verbose_name='Сертификат')),
            ],
            options={
                'verbose_name': 'Пән',
                'verbose_name_plural': 'Пәндер',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Сабақтың уақыты (мин)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.chapter', verbose_name='Модуль')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.subject', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Сабақ',
                'verbose_name_plural': 'Сабақтар',
            },
        ),
        migrations.CreateModel(
            name='FrameContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='URL iframe сілтеме')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_contents', to='core.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Фрейм контент',
                'verbose_name_plural': 'Фрейм контенттер',
            },
        ),
        migrations.CreateModel(
            name='LessonDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('file', models.FileField(blank=True, null=True, upload_to='core/models/lesson/docs/', verbose_name='Файл')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='core.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Сабақ құжаты',
                'verbose_name_plural': 'Сабақ құжаттары',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Жауап мәтіні')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Дұрыс жауап')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Балл')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question', verbose_name='Сұрақ')),
            ],
            options={
                'verbose_name': 'Жауап нұсқасы',
                'verbose_name_plural': 'Жауап нұсқалары',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.subject', verbose_name='Пән'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Тапсырма сұрақтары')),
                ('total_score', models.PositiveIntegerField(default=100, verbose_name='Жалпы балл')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Тапсырма',
                'verbose_name_plural': 'Тапсырмалар',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('total_score', models.PositiveIntegerField(default=100, verbose_name='Жалпы балл')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесттер',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.test', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тақырыбы')),
                ('content', models.TextField(verbose_name='Мәтін')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_contents', to='core.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Мәтін контент',
                'verbose_name_plural': 'Мәтін контенттер',
            },
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL сілтеме')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Видео уақыт')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_contents', to='core.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Видео контент',
                'verbose_name_plural': 'Видео контенттер',
            },
        ),
    ]
