# Generated by Django 5.2.3 on 2025-07-22 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chapter_question_subject_lesson_framecontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_score', models.PositiveSmallIntegerField(default=0, verbose_name='Пәннің жалпы бағасы (%)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Орындалды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Басталған уақыты')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Орындалған уақыты')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to='core.subject', verbose_name='Пән')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Қолданушының пәні',
                'verbose_name_plural': 'Қолданушының пәндері',
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='UserChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Бөлімнің жалпы бағасы (%)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Орындалды')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chapters', to='core.chapter', verbose_name='Бөлім')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chapters', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
                ('user_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chapters', to='core.usersubject', verbose_name='Қолданушының пәндері')),
            ],
            options={
                'verbose_name': 'Қолданушының пән бөлімі',
                'verbose_name_plural': 'Қолданушының пән бөлімдері',
            },
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Сабақтың бағасы (%)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Орындалды')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Орындалған уақыты')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='core.lesson', verbose_name='Сабақ')),
                ('user_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='core.usersubject', verbose_name='Қолданушының пәні')),
            ],
            options={
                'verbose_name': 'Қолданушының сабағы',
                'verbose_name_plural': 'Қолданушының сабақтары',
                'unique_together': {('user_subject', 'lesson')},
            },
        ),
    ]
