# Generated by Django 5.2.3 on 2025-10-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_usertableanswer_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quarter',
            field=models.CharField(choices=[('1', '1-тоқсан'), ('2', '2-тоқсан'), ('3', '3-тоқсан'), ('4', '4-тоқсан')], default='1', max_length=16, verbose_name='Тоқсан'),
        ),
    ]
