# Generated by Django 5.2.3 on 2025-10-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_lesson_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('lesson', 'Сабақ'), ('chapter', 'БЖБ'), ('quarter', 'ТЖБ')], default='lesson', max_length=32, verbose_name='Сабақ түрі'),
        ),
    ]
