# Generated by Django 5.2.3 on 2025-12-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Сабақтың нөмері'),
        ),
    ]
